jmg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls.main', namespace='account')),
    path('company/', include('company.urls.main', namespace='company')),
    path('quarry/', include('quarry.urls.main', namespace='quarry')),
    path('mine/', include('mine.urls.main', namespace='mine')),
    path('mineral/', include('mineral.urls.main', namespace='mineral')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('report/', include('report.urls.main', namespace='report')),
    path('', RedirectView.as_view(pattern_name='dashboard:dashboard'))
]

mineral/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from account.models import User, Profile
from quarry.models import Data, YEAR_CHOICES, current_year


class Choices:
    BAUXITE = 'BAUXITE'
    TINORE = 'TIN ORE'
    IRONORE = 'IRON ORE'
    ANTIMONY = 'ANTIMONY'
    COAL = 'COAL'
    DIMENSIONSTONE = 'DIMENSION STONE'
    FELDSPAR = 'FELDSPAR'
    GALENA = 'GALENA'
    LIMESTONE = 'BATU KAPUR'
    KAOLIN = 'KAOLIN'
    CUPRUM = 'CUPRUM'
    BALLCLAY = 'BALL CLAY'
    MANGANESE = 'MANGANESE'
    SHALE = 'SHALE'
    MICA = 'MICA'
    SILVER = 'SILVER'
    SILICASAND = 'SILICA SAND'
    TUNGSTEN = 'TUNGSTEN'
    GOLD = 'GOLD'
    GRAPHITE = 'GRAPHITE'
    ILMENITE = 'ILMENITE'
    STRUVERIT = 'STRUVERIT'
    MONAZITE = 'MONASIT'
    ZIRCON = 'ZIRKON'
    RUTILE = 'RUTIL'
    XENOTIME = 'XENOTIM'
    AMANG = 'AMANG'
    TYPES_OF_MINERAL = [
        (BAUXITE, _('Bauksite/Bauksit')),
        (TINORE, _('Tin Ore/Bijih Timah')),
        (IRONORE, _('Iron Ore/Bijih Besi')),
        (ANTIMONY, _('Antimony/Antimoni')),
        (COAL, _('Coal/Arang Batu')),
        (DIMENSIONSTONE, _('Dimension Stone/Batu Dimensi')),
        (FELDSPAR, _('Feldspar/Felspar')),
        (GALENA, _('Galena/Galena')),
        (LIMESTONE, _('Limestone/Batu Kapur')),
        (KAOLIN, _('Kaolin')),
        (CUPRUM, _('Kuprum')),
        (BALLCLAY, _('Ball Clay/Lempung Bebola')),
        (MANGANESE, _('Manganese/Mangan')),
        (MICA, _('Mica/Mika')),
        (SILVER, _('Silver/Perak')),
        (SILICASAND, _('Silica Sand/Pasir Silika')),
        (TUNGSTEN, _('Tungsten')),
        (GOLD, _('Gold/Emas')),
        (GRAPHITE, _('Graphite/Grafit')),
        (ILMENITE, _('Ilmenite/Ilmenit')),
        (STRUVERIT, _('Struverit/Struverit')),
        (MONAZITE, _('Graphite/Grafit')),
        (ZIRCON, _('Zircon/Zirkon')),
        (RUTILE, _('Rutile/Rutil')),
        (XENOTIME, _('Xenotime/Xenotim')),
        (AMANG, _('Amang/Amang')),
    ]

    KG = 'KG'
    M3 = 'M3'
    GRAM = 'GRAM'
    TAN = 'TAN'

    UNIT_CHOICES = [
        (KG, _('Kilogram')),
        (M3, _('Meter Persegi')),
        (GRAM, _('Gram')),
        (TAN, _('Tan')),

    ]


class ProcessFactory(models.Model):
    name = models.CharField(_("nama"), max_length=255)
    license_no = models.CharField(
        _("no. lesen memproses mineral"), max_length=255)
    state = models.CharField(_("negeri"), max_length=3,
                             choices=Profile.STATE_CHOICES)
    status = models.BooleanField(_("status"), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "kilang proses"
        verbose_name_plural = "kilang proses"

    def __str__(self):
        return self.name

    def get_update_url(self):
        return reverse("mineral:state_admin:process_factory_update", kwargs={"pk": self.pk})

    def get_toggle_active_url(self):
        return reverse("mineral:state_admin:process_factory_toggle_active", kwargs={"pk": self.pk})

    def get_manager_create_url(self):
        return reverse("mineral:state_admin:manager_create", kwargs={"pk": self.pk})


class ProcessManager(models.Model):
    user = models.OneToOneField(User, verbose_name=_(
        "user"), on_delete=models.CASCADE, primary_key=True)
    factory = models.OneToOneField(ProcessFactory, verbose_name=_(
        "kilang"), on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "pengurus lesen memproses"
        verbose_name_plural = "pengurus lesen memproses"

    def __str__(self):
        return f'{self.user}'

    def get_update_url(self):
        return reverse("mineral:state_admin:manager_update", kwargs={"pk": self.pk})

    def get_toggle_active_url(self):
        return reverse("mineral:state_admin:manager_toggle_active", kwargs={"pk": self.pk})


class ProcessData(models.Model):
    manager = models.ForeignKey(ProcessManager, verbose_name=_(
        "pengurus"), on_delete=models.SET_NULL, related_name='process_data', null=True)
    factory = models.ForeignKey(ProcessFactory, verbose_name=_(
        "kilang"), on_delete=models.SET_NULL, related_name='data', null=True)
    state = models.CharField(_("negeri"), max_length=3,
                             choices=Profile.STATE_CHOICES)
    month = models.PositiveIntegerField(
        _("bulan"), choices=Data.MONTH_CHOICES)
    year = models.PositiveIntegerField(
        _("tahun"), choices=YEAR_CHOICES, default=current_year)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "data lesen memproses"
        verbose_name_plural = "data lesen memproses"

    def __str__(self):
        return f'{self.factory} - {self.pk}'

    def get_absolute_url(self):
        return reverse("mineral:data_detail", kwargs={"pk": self.pk})

    def get_state_absolute_url(self):
        return reverse("mineral:state:data_detail", kwargs={"pk": self.pk})

    def get_state_admin_absolute_url(self):
        return reverse("mineral:state_admin:data_detail", kwargs={"pk": self.pk})

    def get_state_admin_success_url(self):
        return reverse("mineral:state_admin:data_success_detail", kwargs={"pk": self.pk})

    # def get_hq_success_url(self):
    #     return reverse("mineral:hq:data_success_detail", kwargs={"pk": self.pk})

    # def get_hq_absolute_url(self):
    #     return reverse("mineral:hq:data_detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("mineral:process_statistic_edit", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("mineral:data_delete", kwargs={"pk": self.pk})

    def get_last_approval(self):
        return self.approvals.last()


class ProcessStatistic(models.Model):
    data = models.ForeignKey(ProcessData, verbose_name=_(
        "data"), on_delete=models.CASCADE, related_name="statistics")
    mineral_type = models.CharField(
        _("jenis mineral"), max_length=255, choices=Choices.TYPES_OF_MINERAL)
    quantity_unit = models.CharField(
        _("unit kuantiti"), max_length=255, choices=Choices.UNIT_CHOICES, default=Choices.TAN)
    initial_stock = models.DecimalField(
        _("stok awal bulan"), max_digits=15, decimal_places=2)
    external_sources = models.DecimalField(
        _("pembelian dari punca luar"), max_digits=15, decimal_places=2)
    production = models.DecimalField(
        _("pengeluaran"), max_digits=15, decimal_places=2)
    total = models.DecimalField(
        _("jumlah"), max_digits=15, decimal_places=2)
    sold = models.DecimalField(
        _("penjualan"), max_digits=15, decimal_places=2)
    final_stock = models.DecimalField(
        _("stock akhir bulan"), max_digits=15, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "perangkaan lesen proses"
        verbose_name_plural = "perangkaan lesen proses"

    def __str__(self):
        return f"{self.get_mineral_type_display()} - {self.data}"

    def get_absolute_url(self):
        return reverse("mineral:process_statistic_detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("mineral:process_statistic_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("mineral:process_statistic_delete", kwargs={"pk": self.pk})


class ProcessSubmission(models.Model):
    data = models.ForeignKey(ProcessData, verbose_name=_(
        "data"), on_delete=models.CASCADE, related_name="submission")
    mineral_type = models.CharField(
        _("jenis mineral"), max_length=255, choices=Choices.TYPES_OF_MINERAL)
    quantity_unit = models.CharField(
        _("unit kuantiti"), max_length=255, choices=Choices.UNIT_CHOICES, default=Choices.TAN)
    quantity = models.DecimalField(
        _("kuantiti"), max_digits=15, decimal_places=2)
    buyer = models.CharField(_("pembeli"), max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "statistic lesen process"
        verbose_name_plural = "statistic lesen process"

    def __str__(self):
        return f"{self.get_mineral_type_display()} - {self.data}"

    def get_absolute_url(self):
        return reverse("mineral:process_submission_detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("mineral:process_submission_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("mineral:process_submission_delete", kwargs={"pk": self.pk})


class LocalOperator(models.Model):
    data = models.OneToOneField(ProcessData, verbose_name=_(
        "data"), on_delete=models.CASCADE, primary_key=True)
    male_manager = models.IntegerField(_("pengurus lelaki"))
    female_manager = models.IntegerField(_("pengurus perempuan"))
    male_professional = models.IntegerField(_("profesional lelaki"))
    female_professional = models.IntegerField(_("profesional perempuan"))
    male_technical = models.IntegerField(_("teknikal lelaki"))
    female_technical = models.IntegerField(_("teknikal perempuan"))
    male_clerk = models.IntegerField(_("kerani lelaki"))
    female_clerk = models.IntegerField(_("kerani perempuan"))
    male_labor = models.IntegerField(_("buruh lelaki"))
    female_labor = models.IntegerField(_("buruh perempuan"))
    total_male = models.IntegerField(_("jumlah lelaki"))
    total_female = models.IntegerField(_("jumlah perempuan"))
    total_male_salary = models.DecimalField(
        _("jumlah upah gaji lelaki"), max_digits=15, decimal_places=2)
    total_female_salary = models.DecimalField(

account/views/state.py
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404

from ..models import User


class UserListView(ListView):
    template_name = 'account/state/user/list.html'
    model = User
    paginate_by = 8
    ordering = ['-id']

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            profile__state=self.request.user.profile.state,
            groups__name__in=['Industry'])
        try:
            name = self.request.GET['q']
        except:
            name = ''
        if (name != ''):
            object_list = queryset.filter(username__icontains=name)
        else:
            object_list = queryset
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Senarai Pengguna Sistem'
        return context


def user_detail(request, pk):
    each_user = get_object_or_404(User, pk=pk)

    context = {
        'each_user': each_user,
        'title': 'Maklumat Pengguna',
    }

    return render(request, 'account/state/user/detail.html', context)

company/views/state.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView

from ..models import Company, Employee


class CompanyListView(ListView):
    template_name = 'company/state/list.html'
    model = Company
    paginate_by = 8
    ordering = ['-created_at']

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            state=self.request.user.profile.state)
        try:
            name = self.request.GET['q']
        except:
            name = ''
        if (name != ''):
            object_list = queryset.filter(name__icontains=name)
        else:
            object_list = queryset
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Senarai Syarikat'
        return context


def company_detail(request, pk):
    company = get_object_or_404(Company, pk=pk)
    employee_list = Employee.objects.filter(company=company)

    try:
        name = request.GET['q']
    except:
        name = ''
    if (name != ''):
        employee_list = employee_list.filter(user__username__icontains=name)

    page = request.GET.get('page', 1)

    paginator = Paginator(employee_list, 10)
    try:
        employee_list = paginator.page(page)
    except PageNotAnInteger:
        employee_list = paginator.page(1)
    except EmptyPage:
        employee_list = paginator.page(paginator.num_pages)

    context = {
        'company': company,
        'employee_list': employee_list,
        'title': 'Maklumat Syarikat',
    }

    return render(request, 'company/state/detail.html', context)

templates/mine/state/miner_data/list.html
{% extends 'layouts/base.html' %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">{{ title }}</h1>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <div class="row">
        {% comment %} <div class="col justify-content-end">
          <form action="." method="GET">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search" name="q" autocomplete="off">
              <div class="input-group-append">
                <button type="submit" class="btn btn-primary">Search mine</button>
              </div>
            </div>
          </form>
        </div> {% endcomment %}
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-12">
          <table class="table table-hover">
            <thead class="thead-dark">
              <tr>
                <th scope="col">No</th>
                <th scope="col">Nama Syarikat</th>
                <th scope="col">Alamat Syarikat</th>
                <th scope="col">Lokasi Lombong</th>
                <th scope="col">Bulan/Tahun</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for miner_data in object_list %}
              {% with company=miner_data.miner.miner.employee.company mine_miner=miner_data.miner mine=miner_data.mine last_approval=miner_data.get_last_approval %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ company.name }}</td>
                <td>{{ company.address1 }}</td>
                <td>{{ mine }}</td>
                <td>{{ miner_data.get_month_display }} {{ miner_data.year }}</td>
                <td>
                  {% if last_approval %}
                  {% if last_approval.admin_approved == True %}
                  <span class="text-success">Successful</span>
                  {% elif last_approval.state_approved == False or last_approval.admin_approved == False %}
                  <span class="text-danger">Rejected</span>
                  <button class="btn btn-sm btn-secondary" data-toggle="modal" data-target="#rejectCommentModal"
                    data-id="{{ miner_data.id }}">
                    <i class=" far fa-eye"></i>
                  </button>
                  {% else %}
                  <span class="text-warning">In Process</span>
                  {% endif %}
                  {% else %}
                  <span class="text-info">Draft</span>
                  {% endif %}
                </td>
                <td>
                  <a href="{{ miner_data.get_state_absolute_url }}" class="badge badge-sm badge-secondary">
                    <i class="far fa-eye"></i>
                  </a>
                </td>
              </tr>
              {% endwith %}
              {% endfor %}
            </tbody>
          </table>

          {% with pagin=page_obj %}
          {% include 'layouts/includes/_pagination.html' %}
          {% endwith %}
        </div>
      </div>
    </div>
  </div>

</div>
<!-- /.container-fluid -->

<!-- Reject Comment Modal-->
<div class="modal fade" id="rejectCommentModal" tabindex="-1" role="dialog" aria-labelledby="rejectCommentModal"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="rejectCommentModalLabel">Comment</h4>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <span id="comment"></span>
      </div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block extra_js %}
<script>
  $('#rejectCommentModal').on('show.bs.modal', function (event) {
    const button = $(event.relatedTarget)
    const id = button.data('id')
    const modal = $(this)
    $.ajax({
      url: `${id}/get-comment/`,
      success: function (result) {
        modal.find('#comment').text(result)
      }
    });
  })
</script>
{% endblock extra_js %}