jmg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls.main', namespace='account')),
    path('company/', include('company.urls.main', namespace='company')),
    path('quarry/', include('quarry.urls.main', namespace='quarry')),
    path('mine/', include('mine.urls.main', namespace='mine')),
    path('mineral/', include('mineral.urls.main', namespace='mineral')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('report/', include('report.urls.main', namespace='report')),
    path('', RedirectView.as_view(pattern_name='dashboard:dashboard'))
]

mineral/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from account.models import User, Profile
from quarry.models import Data, YEAR_CHOICES, current_year


class Choices:
    BAUXITE = 'BAUXITE'
    TINORE = 'TIN ORE'
    IRONORE = 'IRON ORE'
    ANTIMONY = 'ANTIMONY'
    COAL = 'COAL'
    DIMENSIONSTONE = 'DIMENSION STONE'
    FELDSPAR = 'FELDSPAR'
    GALENA = 'GALENA'
    LIMESTONE = 'BATU KAPUR'
    KAOLIN = 'KAOLIN'
    CUPRUM = 'CUPRUM'
    BALLCLAY = 'BALL CLAY'
    MANGANESE = 'MANGANESE'
    SHALE = 'SHALE'
    MICA = 'MICA'
    SILVER = 'SILVER'
    SILICASAND = 'SILICA SAND'
    TUNGSTEN = 'TUNGSTEN'
    GOLD = 'GOLD'
    GRAPHITE = 'GRAPHITE'
    ILMENITE = 'ILMENITE'
    STRUVERIT = 'STRUVERIT'
    MONAZITE = 'MONASIT'
    ZIRCON = 'ZIRKON'
    RUTILE = 'RUTIL'
    XENOTIME = 'XENOTIM'
    AMANG = 'AMANG'
    TYPES_OF_MINERAL = [
        (BAUXITE, _('Bauksite/Bauksit')),
        (TINORE, _('Tin Ore/Bijih Timah')),
        (IRONORE, _('Iron Ore/Bijih Besi')),
        (ANTIMONY, _('Antimony/Antimoni')),
        (COAL, _('Coal/Arang Batu')),
        (DIMENSIONSTONE, _('Dimension Stone/Batu Dimensi')),
        (FELDSPAR, _('Feldspar/Felspar')),
        (GALENA, _('Galena/Galena')),
        (LIMESTONE, _('Limestone/Batu Kapur')),
        (KAOLIN, _('Kaolin')),
        (CUPRUM, _('Kuprum')),
        (BALLCLAY, _('Ball Clay/Lempung Bebola')),
        (MANGANESE, _('Manganese/Mangan')),
        (MICA, _('Mica/Mika')),
        (SILVER, _('Silver/Perak')),
        (SILICASAND, _('Silica Sand/Pasir Silika')),
        (TUNGSTEN, _('Tungsten')),
        (GOLD, _('Gold/Emas')),
        (GRAPHITE, _('Graphite/Grafit')),
        (ILMENITE, _('Ilmenite/Ilmenit')),
        (STRUVERIT, _('Struverit/Struverit')),
        (MONAZITE, _('Graphite/Grafit')),
        (ZIRCON, _('Zircon/Zirkon')),
        (RUTILE, _('Rutile/Rutil')),
        (XENOTIME, _('Xenotime/Xenotim')),
        (AMANG, _('Amang/Amang')),
    ]

    KG = 'KG'
    M3 = 'M3'
    GRAM = 'GRAM'
    TAN = 'TAN'

    UNIT_CHOICES = [
        (KG, _('Kilogram')),
        (M3, _('Meter Persegi')),
        (GRAM, _('Gram')),
        (TAN, _('Tan')),

    ]


class ProcessFactory(models.Model):
    name = models.CharField(_("nama"), max_length=255)
    license_no = models.CharField(
        _("no. lesen memproses mineral"), max_length=255)
    state = models.CharField(_("negeri"), max_length=3,
                             choices=Profile.STATE_CHOICES)
    status = models.BooleanField(_("status"), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "kilang proses"
        verbose_name_plural = "kilang proses"

    def __str__(self):
        return self.name

    def get_update_url(self):
        return reverse("mineral:state_admin:process_factory_update", kwargs={"pk": self.pk})

    def get_toggle_active_url(self):
        return reverse("mineral:state_admin:process_factory_toggle_active", kwargs={"pk": self.pk})

    def get_manager_create_url(self):
        return reverse("mineral:state_admin:manager_create", kwargs={"pk": self.pk})


class ProcessManager(models.Model):
    user = models.OneToOneField(User, verbose_name=_(
        "user"), on_delete=models.CASCADE, primary_key=True)
    factory = models.OneToOneField(ProcessFactory, verbose_name=_(
        "kilang"), on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "pengurus lesen memproses"
        verbose_name_plural = "pengurus lesen memproses"

    def __str__(self):
        return f'{self.user}'

    def get_update_url(self):
        return reverse("mineral:state_admin:manager_update", kwargs={"pk": self.pk})

    def get_toggle_active_url(self):
        return reverse("mineral:state_admin:manager_toggle_active", kwargs={"pk": self.pk})


class ProcessData(models.Model):
    manager = models.ForeignKey(ProcessManager, verbose_name=_(
        "pengurus"), on_delete=models.SET_NULL, related_name='process_data', null=True)
    factory = models.ForeignKey(ProcessFactory, verbose_name=_(
        "kilang"), on_delete=models.SET_NULL, related_name='data', null=True)
    state = models.CharField(_("negeri"), max_length=3,
                             choices=Profile.STATE_CHOICES)
    month = models.PositiveIntegerField(
        _("bulan"), choices=Data.MONTH_CHOICES)
    year = models.PositiveIntegerField(
        _("tahun"), choices=YEAR_CHOICES, default=current_year)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "data lesen memproses"
        verbose_name_plural = "data lesen memproses"

    def __str__(self):
        return f'{self.factory} - {self.pk}'

    def get_absolute_url(self):
        return reverse("mineral:data_detail", kwargs={"pk": self.pk})

    def get_state_absolute_url(self):
        return reverse("mineral:state:data_detail", kwargs={"pk": self.pk})

    def get_state_admin_absolute_url(self):
        return reverse("mineral:state_admin:data_detail", kwargs={"pk": self.pk})

    def get_state_admin_success_url(self):
        return reverse("mineral:state_admin:data_success_detail", kwargs={"pk": self.pk})

    # def get_hq_success_url(self):
    #     return reverse("mineral:hq:data_success_detail", kwargs={"pk": self.pk})

    # def get_hq_absolute_url(self):
    #     return reverse("mineral:hq:data_detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("mineral:process_statistic_edit", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("mineral:data_delete", kwargs={"pk": self.pk})

    def get_last_approval(self):
        return self.approvals.last()


class ProcessStatistic(models.Model):
    data = models.ForeignKey(ProcessData, verbose_name=_(
        "data"), on_delete=models.CASCADE, related_name="statistics")
    mineral_type = models.CharField(
        _("jenis mineral"), max_length=255, choices=Choices.TYPES_OF_MINERAL)
    quantity_unit = models.CharField(
        _("unit kuantiti"), max_length=255, choices=Choices.UNIT_CHOICES, default=Choices.TAN)
    initial_stock = models.DecimalField(
        _("stok awal bulan"), max_digits=15, decimal_places=2)
    external_sources = models.DecimalField(
        _("pembelian dari punca luar"), max_digits=15, decimal_places=2)
    production = models.DecimalField(
        _("pengeluaran"), max_digits=15, decimal_places=2)
    total = models.DecimalField(
        _("jumlah"), max_digits=15, decimal_places=2)
    sold = models.DecimalField(
        _("penjualan"), max_digits=15, decimal_places=2)
    final_stock = models.DecimalField(
        _("stock akhir bulan"), max_digits=15, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "perangkaan lesen proses"
        verbose_name_plural = "perangkaan lesen proses"

    def __str__(self):
        return f"{self.get_mineral_type_display()} - {self.data}"

    def get_absolute_url(self):
        return reverse("mineral:process_statistic_detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("mineral:process_statistic_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("mineral:process_statistic_delete", kwargs={"pk": self.pk})


class ProcessSubmission(models.Model):
    data = models.ForeignKey(ProcessData, verbose_name=_(
        "data"), on_delete=models.CASCADE, related_name="submission")
    mineral_type = models.CharField(
        _("jenis mineral"), max_length=255, choices=Choices.TYPES_OF_MINERAL)
    quantity_unit = models.CharField(
        _("unit kuantiti"), max_length=255, choices=Choices.UNIT_CHOICES, default=Choices.TAN)
    quantity = models.DecimalField(
        _("kuantiti"), max_digits=15, decimal_places=2)
    buyer = models.CharField(_("pembeli"), max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "statistic lesen process"
        verbose_name_plural = "statistic lesen process"

    def __str__(self):
        return f"{self.get_mineral_type_display()} - {self.data}"

    def get_absolute_url(self):
        return reverse("mineral:process_submission_detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("mineral:process_submission_update", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("mineral:process_submission_delete", kwargs={"pk": self.pk})


class LocalOperator(models.Model):
    data = models.OneToOneField(ProcessData, verbose_name=_(
        "data"), on_delete=models.CASCADE, primary_key=True)
    male_manager = models.IntegerField(_("pengurus lelaki"))
    female_manager = models.IntegerField(_("pengurus perempuan"))
    male_professional = models.IntegerField(_("profesional lelaki"))
    female_professional = models.IntegerField(_("profesional perempuan"))
    male_technical = models.IntegerField(_("teknikal lelaki"))
    female_technical = models.IntegerField(_("teknikal perempuan"))
    male_clerk = models.IntegerField(_("kerani lelaki"))
    female_clerk = models.IntegerField(_("kerani perempuan"))
    male_labor = models.IntegerField(_("buruh lelaki"))
    female_labor = models.IntegerField(_("buruh perempuan"))
    total_male = models.IntegerField(_("jumlah lelaki"))
    total_female = models.IntegerField(_("jumlah perempuan"))
    total_male_salary = models.DecimalField(
        _("jumlah upah gaji lelaki"), max_digits=15, decimal_places=2)
    total_female_salary = models.DecimalField(

templates/mineral/data/process_submission/detail.html
{% extends 'layouts/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">{{ title }}</h1>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-12">
          <table class="table table-bordered table-sm">
            <thead class="thead-light">
              <tr>
                <th scope="col"></th>
                <th scope="col" style="text-align: center;">AMAUN (MT)</th>
                <th scope="col" style="text-align: center;">NILAI/TAN (RM)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th>CRUSHER RUN</th>
                <td style="text-align: right;">{{ sales_submission.crusher_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.crusher_worth }}</td>
              </tr>
              <tr>
                <th>QUARRY DUST</th>
                <td style="text-align: right;">{{ sales_submission.dust_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.dust_worth }}</td>
              </tr>
              <tr>
                <th>QUARRY WASTE</th>
                <td style="text-align: right;">{{ sales_submission.waste_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.waste_worth }}</td>
              </tr>
              <tr>
                <th>1/8"</th>
                <td style="text-align: right;">{{ sales_submission.inch_1_8_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.inch_1_8_worth }}</td>
              </tr>
              <tr>
                <th>3/8"</th>
                <td style="text-align: right;">{{ sales_submission.inch_3_8_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.inch_3_8_worth }}</td>
              </tr>
              <tr>
                <th>5/8"</th>
                <td style="text-align: right;">{{ sales_submission.inch_5_8_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.inch_5_8_worth }}</td>
              </tr>
              <tr>
                <th>3/4"</th>
                <td style="text-align: right;">{{ sales_submission.inch_3_4_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.inch_3_4_worth }}</td>
              </tr>
              <tr>
                <th>1"</th>
                <td style="text-align: right;">{{ sales_submission.inch_1_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.inch_1_worth }}</td>
              </tr>
              <tr>
                <th>1 1/2"</th>
                <td style="text-align: right;">{{ sales_submission.inch_1_1_2_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.inch_1_1_2_worth }}</td>
              </tr>
              <tr>
                <th>2"</th>
                <td style="text-align: right;">{{ sales_submission.inch_2_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.inch_2_worth }}</td>
              </tr>
              <tr>
                <th>3" x 5"</th>
                <td style="text-align: right;">{{ sales_submission.inch_3x5_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.inch_3x5_worth }}</td>
              </tr>
              <tr>
                <th>6" x 9"</th>
                <td style="text-align: right;">{{ sales_submission.inch_6x9_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.inch_6x9_worth }}</td>
              </tr>
              <tr>
                <th>BLOCK</th>
                <td style="text-align: right;">{{ sales_submission.block_amount }}</td>
                <td style="text-align: right;">{{ sales_submission.block_worth }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col-4 col-lg-3 mt-3 ml-auto">
          <a href="{{ prev_link }}" class="btn btn-secondary btn-user btn-block">
            Sebelumnya
          </a>
        </div>
        <div class="col-4 col-lg-3 mt-3">
          <a href="{{ next_link }}" class="btn btn-info btn-user btn-block">
            Seterusnya
          </a>
        </div>
      </div>
    </div>
  </div>

</div>
<!-- /.container-fluid -->
{% endblock content %}

templates/mineral/data/process_submission/form.html
{% extends 'layouts/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">{{ title }}</h1>

  <form action="." method="post">
    {% csrf_token %}

    <div class="row">
      <div class="col-lg-12">
        {{ form|crispy }}
      </div>
    </div>

    <div class="row">
      <div class="col-4 col-lg-3 mt-3 ml-auto">
        <button type="submit" class="btn btn-info btn-user btn-block">
          Hantar
        </button>
      </div>
    </div>
  </form>

</div>
<!-- /.container-fluid -->
{% endblock content %}

{% block extra_js %}
<script>
  const amount = document.getElementById('id_amount')
  const worth = document.getElementById('id_worth')
  const total = document.getElementById('id_total')

  const set_total = () => {
    let total_submission = (parseFloat(amount.value) || 0) * (parseFloat(worth.value) || 0)
    total.value = total_submission
  }

  amount.addEventListener("change", () => {
    set_total()
  })

  worth.addEventListener("change", () => {
    set_total()
  })
</script>
{% endblock extra_js %}

templates/mineral/data/process_submission/list.html
{% extends 'layouts/base.html' %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">{{ title }}</h1>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <div class="row">
        <div class="col">
          <a href="{% url 'mineral:process_submission_create' data.pk %}" class="btn btn-primary">Tambah Penyerahan
            Jualan</a>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-lg-12">
          <table class="table table-hover">
            <thead class="thead-dark">
              <tr>
                <th scope="col">No</th>
                <th scope="col">Jenis Mineral</th>
                <th scope="col">Unit</th>
                <th scope="col">Kuantiti</th>
                <th scope="col">Pembeli</th>
                <th scope="col">Tindakan</th>
              </tr>
            </thead>
            <tbody>
              {% for process_submission in process_submission_list %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ process_submission.mineral_type }}</td>
                <td>{{ process_submission.get_quantity_unit_display }}</td>
                <td>{{ process_submission.quantity }}</td>
                <td>{{ process_submission.buyer }}</td>
                <td>
                  <a href="{{ process_submission.get_edit_url }}" class="badge badge-sm badge-info">Ubah</a>
                  <a href="" class="badge badge-sm badge-danger" data-toggle="modal" data-target="#deleteModal"
                    data-href="{{ process_submission.get_delete_url }}">Padam</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>

      <div class="row">
        <div class="col-4 col-lg-3 mt-3 ml-auto">
          <a href="{{ prev_link }}" class="btn btn-secondary btn-user btn-block">
            Sebelumnya
          </a>
        </div>
        <div class="col-4 col-lg-3 mt-3">
          <a href="{{ next_link }}" class="btn btn-info btn-user btn-block">
            Simpan & Seterusnya
          </a>
        </div>
      </div>
    </div>
  </div>

</div>
<!-- /.container-fluid -->

<!-- delete Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="deleteModalLabel">Padam Data</h4>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <form id="deleteForm" action="#" method="post">
        <div class="modal-body">
          {% csrf_token %}
          Anda yakin mahu padam data ini?
        </div>
        <div class="modal-footer">
          <button class="btn btn-danger" type="submit">Padam</button>
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Tutup</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block extra_js %}
<script>
  // delete deta
  $('#deleteModal').on('show.bs.modal', function (event) {
    const button = $(event.relatedTarget)
    const href = button.data('href')
    const modal = $(this)
    modal.find('#deleteForm').attr('action', href)
  })
</script>
{% endblock extra_js %}

templates/mineral/data/process_submission/readonly.html
{% extends 'layouts/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-4 text-gray-800">{{ title }}</h1>

  <div class="row">
    <div class="col-lg-12">
      <div class="row mb-3">
        <div class="offset-4 col-4"><b>AMAUN (MT)</b></div>
        <div class="col-4"><b>NILAI/TAN (RM)</b></div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>Crusher Run</b></label>
        <div class="col-4">
          {{ form.crusher_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.crusher_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>Quarry Dust</b></label>
        <div class="col-4">
          {{ form.dust_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.dust_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>Quarry Waste</b></label>
        <div class="col-4">
          {{ form.waste_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.waste_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>1/8"</b></label>
        <div class="col-4">
          {{ form.inch_1_8_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.inch_1_8_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>3/8"</b></label>
        <div class="col-4">
          {{ form.inch_3_8_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.inch_3_8_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>5/8"</b></label>
        <div class="col-4">
          {{ form.inch_5_8_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.inch_5_8_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>3/4"</b></label>
        <div class="col-4">
          {{ form.inch_3_4_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.inch_3_4_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>1"</b></label>
        <div class="col-4">
          {{ form.inch_1_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.inch_1_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>1 1/2"</b></label>
        <div class="col-4">
          {{ form.inch_1_1_2_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.inch_1_1_2_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>2"</b></label>
        <div class="col-4">
          {{ form.inch_2_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.inch_2_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>3" x 5"</b></label>
        <div class="col-4">
          {{ form.inch_3x5_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.inch_3x5_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>6" x 9"</b></label>
        <div class="col-4">
          {{ form.inch_6x9_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.inch_6x9_worth|as_crispy_field }}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-4"><b>Block</b></label>
        <div class="col-4">
          {{ form.block_amount|as_crispy_field }}
        </div>
        <div class="col-4">
          {{ form.block_worth|as_crispy_field }}
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-4 col-lg-3 mt-3 ml-auto">
      <a href="{{ prev_link }}" class="btn btn-secondary btn-user btn-block">
        Sebelumnya
      </a>
    </div>
    <div class="col-4 col-lg-3 mt-3">
      <a href="{{ next_link }}" class="btn btn-info btn-user btn-block">
        Seterusnya
      </a>
    </div>
  </div>

</div>
<!-- /.container-fluid -->
{% endblock content %}